syntax = "proto3";

import "com/obsbot/happyinn/apps/happyinninobsbot/data/dark_theme_config.proto";
import "com/obsbot/happyinn/apps/happyinninobsbot/data/theme_brand.proto";
import "com/obsbot/happyinn/apps/happyinninobsbot/data/sort_config.proto";
import "com/obsbot/happyinn/apps/happyinninobsbot/data/media_layout_mode.proto";
import "com/obsbot/happyinn/apps/happyinninobsbot/data/media_view_mode.proto";

option java_package = "com.obsbot.happyinn.apps.happyinninobsbot.core.datastore";
option java_multiple_files = true;

message UserPreferences {
    reserved 2;
    repeated int32 deprecated_int_followed_topic_ids = 1;
    int32 topicChangeListVersion = 3;
    int32 authorChangeListVersion = 4;
    int32 NewsResourceChangeListVersion = 6;
    repeated int32 deprecated_int_followed_author_ids = 7;
    bool has_done_int_to_string_id_migration = 8;
    repeated string deprecated_followed_topic_ids = 9;
    repeated string deprecated_followed_author_ids = 10;
    repeated string deprecated_bookmarked_News_resource_ids = 11;
    bool has_done_list_to_map_migration = 12;

    // Each map is used to store a set of string IDs. The bool has no meaning, but proto3 doesn't
    // have a Set type so this is the closest we can get to a Set.
    map<string, bool> followed_topic_ids = 13;
    map<string, bool> followed_author_ids = 14;
    map<string, bool> bookmarked_News_resource_ids = 15;
    map<string, bool> viewed_News_resource_ids = 20;

    ThemeBrandProto theme_brand = 16;
    DarkThemeConfigProto dark_theme_config = 17;

    bool should_hide_onboarding = 18;

    bool use_dynamic_color = 19;

    SortByProto sort_by = 21;
    SortOrderProto sort_order = 22;
    bool mark_last_played_media = 23;
    bool show_floating_play_button = 24;
    repeated string exclude_folders = 25;
    MediaViewModeProto media_view_mode = 26;
    MediaLayoutModeProto media_layout_mode = 27;
    bool show_duration_field = 28;
    bool show_extension_field = 29;
    bool show_path_field = 30;
    bool show_resolution_field = 31;
    bool show_size_field = 32;
    bool show_thumbnail_field = 33;
    bool show_played_progress = 34;

    // NEXT AVAILABLE ID: 35

}
